<?php

/**
 * @file
 * Primary module hooks for Hello World module.
 */

use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 * 
 * Make the Promotion Options details component open by default in node creation forms.
 */
function hello_world_form_alter(&$form, FormStateInterface $form_state, $form_id) : void {
  $form_list = [
    'node_accessory_form',
    'node_phone_form',
    'node_article_form',
  ];

  if (in_array($form_id, $form_list)) {
    $form['options']['#open'] = TRUE;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 * 
 * Change access to field_tags in article forms.
 */
function hello_world_form_node_article_form_alter(&$form, FormStateInterface $form_state, $form_id) : void {
  // Use method chaining, avoid creating a variable to hold the service.
  // Next two lines are equivalent.  
  // $form['field_tags']['#access'] = \Drupal::currentUser()->hasPermission('tag articles');
  // $form['field_tags']['#access'] = \Drupal::service('current_user')->hasPermission('tag articles');

  // Next two lines are equivalent.
  // $user = \Drupal::currentUser();
  $user = \Drupal::service('current_user');
  $form['field_tags']['#access'] = $user->hasPermission('tag articles');
}